catalog/urls.py
from django.urls import path

from catalog.views import (index,
                           TopicListView,
                           NewspaperListView,
                           NewspaperDetailView,
                           RedactorListView,
                           RedactorDetailView,
                           TopicCreateView,
                           TopicUpdateView,
                           TopicDeleteView,
                           NewspaperCreateView,
                           NewspaperUpdateView,
                           NewspaperDeleteView,
                           RedactorDeleteView,
                           RedactorUpdateView,
                           RedactorCreateView,
                           )

urlpatterns = [
    path("", index, name="index"),
    path(
        "topics/", TopicListView.as_view(),
        name="topic-list"
    ),
    path(
        "topics/create/",
        TopicCreateView.as_view(),
        name="topic-create",
    ),
    path(
        "topics/<int:pk>/update/",
        TopicUpdateView.as_view(),
        name="topic-update"
    ),
    path(
        "topics/<int:pk>/delete/",
        TopicDeleteView.as_view(),
        name="topic-delete"
    ),
    path(
        "newspapers/",
        NewspaperListView.as_view(),
        name="newspaper-list",
    ),
    path(
        "newspapers/<int:pk>/",
        NewspaperDetailView.as_view(),
        name="newspaper-detail"
    ),
    path("newspapers/create/", NewspaperCreateView.as_view(), name="newspaper-create"),
    path("newspapers/<int:pk>/update/", NewspaperUpdateView.as_view(), name="newspaper-update"),
    path("newspapers/<int:pk>/delete/", NewspaperDeleteView.as_view(), name="newspaper-delete"),
    path(
        "redactors/",
        RedactorListView.as_view(),
        name="redactor-list"
    ),
    path(
        "redactors/<int:pk>/",
        RedactorDetailView.as_view(),
        name="redactor-detail"
    ),
    path("redactors/create/", RedactorCreateView.as_view(), name="redactor-create"),
    path("redactors/<int:pk>/update/", RedactorUpdateView.as_view(),
         name="redactor-update"),
    path("redactors/<int:pk>/delete/", RedactorDeleteView.as_view(),
         name="redactor-delete"),
]

app_name = "catalog"

portfolio/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path("", include("catalog.urls", namespace="catalog")),
                  path("accounts/", include("django.contrib.auth.urls")),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/includes/footer-auth.html
<footer class="footer position-absolute bottom-2 py-2 w-100">
  <div class="container">
    <div class="row align-items-center justify-content-lg-between">
      <div class="col-12 col-md-6 my-auto">
        <div class="copyright text-center text-sm text-white text-lg-start">
          &copy; <a href="https://bit.ly/3fKQZaL" class="font-weight-bold text-white" target="_blank">Creative Tim</a>
          coded by AppSeed.
        </div>
      </div>
      <div class="col-12 col-md-6">
        <ul class="nav nav-footer justify-content-center justify-content-lg-end">
          <li class="nav-item">
            <a href="https://github.com/app-generator/django-material-kit" class="nav-link text-white" target="_blank">Sources</a>
          </li>
          <li class="nav-item">
            <a href="https://appseed.us/support" class="nav-link text-white" target="_blank">Support</a>
          </li>
          <li class="nav-item">
            <a href="https://appseed.us" class="nav-link text-white" target="_blank">AppSeed</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

templates/includes/navigation.html
<!-- Navbar -->
<div class="container position-sticky z-index-sticky top-0">
  <div class="row">
    <div class="col-12">
      <nav
          class="navbar navbar-expand-lg  blur border-radius-xl mt-4 top-0 z-index-3 shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
        <div class="container-fluid px-0">
          <a class="navbar-brand font-weight-bolder ms-sm-3" href="/" rel="tooltip"
             title="Designed and Coded by Creative Tim" data-placement="bottom">
            Newspaper Agency
          </a>
          <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse"
                  data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false"
                  aria-label="Toggle navigation">
              <span class="navbar-toggler-icon mt-2">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </span>
          </button>
          <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0 w-100" id="navigation">
            <ul class="navbar-nav navbar-nav-hover ms-auto">
              <li class="nav-item dropdown dropdown-hover mx-2">
                <a class="nav-link ps-2 d-flex cursor-pointer align-items-center" id="dropdownMenuPages"
                   data-bs-toggle="dropdown" aria-expanded="false">
                  <i class="material-icons opacity-6 me-2 text-md">dashboard</i>
                  Topics
                </a>
                <div class="dropdown-menu dropdown-menu-animation ms-n3 dropdown-md p-3 border-radius-xl mt-0 mt-lg-3"
                     aria-labelledby="dropdownMenuPages">
                  <div class="d-none d-lg-block">
                    <a href="{% url 'catalog:topic-list' %}" class="dropdown-item border-radius-md">
                      <span>List of topics</span>
                    </a>
                    <a href="{% url 'catalog:topic-create' %}" class="dropdown-item border-radius-md">
                      <span>Create topic</span>
                    </a>
                  </div>
                  <div class="d-lg-none">
                    <h6 class="dropdown-header text-dark font-weight-bolder d-flex align-items-center px-1">
                      Landing Pages
                    </h6>
                    <a href="/author.html" class="dropdown-item border-radius-md">
                      <span>Author</span>
                    </a>
                  </div>
                </div>
              </li>
              <li class="nav-item dropdown dropdown-hover mx-2">
                <a class="nav-link ps-2 d-flex cursor-pointer align-items-center" id="dropdownMenuPages"
                   data-bs-toggle="dropdown" aria-expanded="false">
                  <i class="material-icons opacity-6 me-2 text-md">dashboard</i>
                  Newspapers
                </a>
                <div class="dropdown-menu dropdown-menu-animation ms-n3 dropdown-md p-3 border-radius-xl mt-0 mt-lg-3"
                     aria-labelledby="dropdownMenuPages">
                  <div class="d-none d-lg-block">
                    <a href="{% url 'catalog:newspaper-list' %}" class="dropdown-item border-radius-md">
                      <span>List of newspapers</span>
                    </a>
                    <a href="{% url 'catalog:newspaper-create' %}" class="dropdown-item border-radius-md">
                      <span>Create newspaper</span>
                    </a>
                  </div>
                  <div class="d-lg-none">
                    <h6 class="dropdown-header text-dark font-weight-bolder d-flex align-items-center px-1">
                      Landing Pages
                    </h6>
                    <a href="/author.html" class="dropdown-item border-radius-md">
                      <span>Author</span>
                    </a>
                  </div>
                </div>
              </li>
              <li class="nav-item dropdown dropdown-hover mx-2">
                <a class="nav-link ps-2 d-flex cursor-pointer align-items-center" id="dropdownMenuPages"
                   data-bs-toggle="dropdown" aria-expanded="false">
                  <i class="material-icons opacity-6 me-2 text-md">dashboard</i>
                  Redactors
                </a>
                <div class="dropdown-menu dropdown-menu-animation ms-n3 dropdown-md p-3 border-radius-xl mt-0 mt-lg-3"
                     aria-labelledby="dropdownMenuPages">
                  <div class="d-none d-lg-block">
                    <a href="{% url 'catalog:redactor-list' %}" class="dropdown-item border-radius-md">
                      <span>List of redactors</span>
                    </a>
                    <a href="{% url 'catalog:redactor-create' %}" class="dropdown-item border-radius-md">
                      <span>Create redactor</span>
                    </a>
                  </div>
                  <div class="d-lg-none">
                    <h6 class="dropdown-header text-dark font-weight-bolder d-flex align-items-center px-1">
                      Landing Pages
                    </h6>
                    <a href="/author.html" class="dropdown-item border-radius-md">
                      <span>Author</span>
                    </a>
                  </div>
                </div>
              </li>

              {% if request.user.is_authenticated %}
                <li class="nav-item ms-lg-auto">
                  <a class="nav-link nav-link-icon me-2"
                     href="{% url 'logout' %}">
                    <i class="fa fa-sign-out me-1"></i>
                    <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip"
                       data-bs-placement="bottom" title="Sign OUT">Logout</p>
                  </a>
                </li>
              {% endif %}

            </ul>
          </div>
        </div>
      </nav>
      <!-- End Navbar -->
    </div>
  </div>
</div>

templates/includes/pagination.html
{% block pagination %}
  {% if is_paginated %}
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a href="?page={{ page_obj.previous_page_number }}" class="page-link">prev</a>
        </li>
      {% endif %}

      <li class="page-item active">
        <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
      </li>

      {% if page_obj.has_next %}
        <li class="page-item">
          <a href="?page={{ page_obj.next_page_number }}" class="page-link">next</a>
        </li>
      {% endif %}
    </ul>
  {% endif %}
{% endblock %}

templates/includes/scripts.html
<!--   Core JS Files   -->
<script src="/static/assets/js/core/popper.min.js" type="text/javascript"></script>
<script src="/static/assets/js/core/bootstrap.min.js" type="text/javascript"></script>
<script src="/static/assets/js/plugins/perfect-scrollbar.min.js"></script>

<!--  Plugin for TypedJS, full documentation here: https://github.com/inorganik/CountUp.js -->
<script src="/static/assets/js/plugins/countup.min.js"></script>
<script src="/static/assets/js/plugins/choices.min.js"></script>
<script src="/static/assets/js/plugins/prism.min.js"></script>
<script src="/static/assets/js/plugins/highlight.min.js"></script>

<!--  Plugin for Parallax, full documentation here: https://github.com/dixonandmoe/rellax -->
<script src="/static/assets/js/plugins/rellax.min.js"></script>
<!--  Plugin for TiltJS, full documentation here: https://gijsroge.github.io/tilt.js/ -->
<script src="/static/assets/js/plugins/tilt.min.js"></script>
<!--  Plugin for Selectpicker - ChoicesJS, full documentation here: https://github.com/jshjohnson/Choices -->
<script src="/static/assets/js/plugins/choices.min.js"></script>

<!--  Plugin for Parallax, full documentation here: https://github.com/wagerfield/parallax  -->
<script src="/static/assets/js/plugins/parallax.min.js"></script>

<!-- Control Center for Material UI Kit: parallax effects, scripts for the example pages etc -->
<script src="/static/assets/js/material-kit.min.js?v=3.0.0" type="text/javascript"></script>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  {% if user.is_authenticated %}
    <li class="list-group-item">User: <a href="{{ user.get_absolute_url }}">{{ user.get_username }}</a></li>
    <li class="list-group-item"><a href="{% url 'logout' %}?next={{ request.path }}">Logout</a></li>
  {% else %}
    <li class="list-group-item"><a href="{% url 'login' %}?next={{ request.path }}">Login</a></li>
  {% endif %}
  <br>
  <li class="list-group-item"><a href="{% url 'catalog:index' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'catalog:redactor-list' %}">All redactors</a></li>
  <li class="list-group-item"><a href="{% url 'catalog:newspaper-list' %}">All newspapers</a></li>
  <li class="list-group-item"><a href="{% url 'catalog:topic-list' %}">All topics</a></li>
</ul>