catalog/urls.py
from django.urls import path

from catalog.views import (index,
                           TopicListView,
                           NewspaperListView,
                           NewspaperDetailView,
                           RedactorListView,
                           RedactorDetailView,
                           TopicCreateView,
                           TopicUpdateView,
                           TopicDeleteView,
                           NewspaperCreateView,
                           NewspaperUpdateView,
                           NewspaperDeleteView,
                           RedactorDeleteView,
                           RedactorUpdateView,
                           RedactorCreateView,
                           )

urlpatterns = [
    path("", index, name="index"),
    path(
        "topics/", TopicListView.as_view(),
        name="topic-list"
    ),
    path(
        "topics/create/",
        TopicCreateView.as_view(),
        name="topic-create",
    ),
    path(
        "topics/<int:pk>/update/",
        TopicUpdateView.as_view(),
        name="topic-update"
    ),
    path(
        "topics/<int:pk>/delete/",
        TopicDeleteView.as_view(),
        name="topic-delete"
    ),
    path(
        "newspapers/",
        NewspaperListView.as_view(),
        name="newspaper-list",
    ),
    path(
        "newspapers/<int:pk>/",
        NewspaperDetailView.as_view(),
        name="newspaper-detail"
    ),
    path("newspapers/create/", NewspaperCreateView.as_view(), name="newspaper-create"),
    path("newspapers/<int:pk>/update/", NewspaperUpdateView.as_view(), name="newspaper-update"),
    path("newspapers/<int:pk>/delete/", NewspaperDeleteView.as_view(), name="newspaper-delete"),
    path(
        "redactors/",
        RedactorListView.as_view(),
        name="redactor-list"
    ),
    path(
        "redactors/<int:pk>/",
        RedactorDetailView.as_view(),
        name="redactor-detail"
    ),
    path("redactors/create/", RedactorCreateView.as_view(), name="redactor-create"),
    path("redactors/<int:pk>/update/", RedactorUpdateView.as_view(),
         name="redactor-update"),
    path("redactors/<int:pk>/delete/", RedactorDeleteView.as_view(),
         name="redactor-delete"),
]

app_name = "catalog"

portfolio/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path("", include("catalog.urls", namespace="catalog")),
                  path("accounts/", include("django.contrib.auth.urls")),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models


class Topic(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering = ["id"]

    def __str__(self):
        return self.name


class Redactor(AbstractUser):
    years_of_experience = models.IntegerField(null=True, blank=True)

    class Meta:
        verbose_name = "Redactor"
        verbose_name_plural = "Redactors"
        ordering = ["id"]

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"


class Newspaper(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    published_date = models.DateField(null=True)
    topic = models.ForeignKey("Topic", on_delete=models.CASCADE)
    redactors = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="newspapers")

    class Meta:
        ordering = ["id"]

    def __str__(self):
        return self.title

catalog/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from catalog.models import Redactor, Newspaper


class RedactorCreateForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Redactor
        fields = UserCreationForm.Meta.fields + (
         "first_name", "last_name", "years_of_experience"
        )


class RedactorExperienceUpdateForm(forms.ModelForm):
    class Meta:
        model = Redactor
        fields = ("years_of_experience",)


class NewspaperForm(forms.ModelForm):
    redactors = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = Newspaper
        fields = "__all__"


class NewspaperSearchForm(forms.Form):
    title = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by title"})
    )


class RedactorSearchForm(forms.Form):
    username = forms.CharField(
        max_length=63,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by Username"})
    )


class TopicSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name"})
    )

catalog/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from catalog.forms import (
    RedactorCreateForm,
    RedactorExperienceUpdateForm,
    NewspaperForm,
    NewspaperSearchForm,
    TopicSearchForm,
    RedactorSearchForm
    )
from catalog.models import Redactor, Topic, Newspaper


@login_required
def index(request):
    num_redactors = Redactor.objects.count()
    num_topics = Topic.objects.count()
    num_newspapers = Newspaper.objects.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_redactors": num_redactors,
        "num_topics": num_topics,
        "num_newspapers": num_newspapers,
        "num_visits": num_visits + 1,
    }

    return render(request, "catalog/index.html", context=context)


class TopicListView(LoginRequiredMixin, generic.ListView):
    model = Topic
    paginate_by = 5
    queryset = Topic.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        name = self.request.GET.get("name", "")

        context = super(TopicListView, self).get_context_data(**kwargs)
        context["search_form"] = TopicSearchForm(initial={
            "name": name
        })

        return context

    def get_queryset(self):
        form = TopicSearchForm(self.request.GET)

        if form.is_valid():
            return self.queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )

        return self.queryset


class TopicDetailView(LoginRequiredMixin, generic.DetailView):
    model = Topic


class TopicCreateView(LoginRequiredMixin, generic.CreateView):
    model = Topic
    fields = "__all__"
    success_url = reverse_lazy("catalog:topic-list")
    template_name = "catalog/topic_form.html"


class TopicUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Topic
    fields = "__all__"
    success_url = reverse_lazy("catalog:topic-list")
    template_name = "catalog/topic_form.html"


class TopicDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Topic
    success_url = reverse_lazy("catalog:topic-list")
    template_name = "catalog/topic_form_confirm_delete.html"


class ManufacturerUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Topic
    fields = "__all__"
    success_url = reverse_lazy("catalog:topic-list")
    template_name = "catalog/topic_form.html"


class ManufacturerDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Topic
    success_url = reverse_lazy("catalog:topic-list")
    template_name = "catalog/topic_form_confirm_delete.html"


class NewspaperListView(LoginRequiredMixin, generic.ListView):
    model = Newspaper
    queryset = Newspaper.objects.all()
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(NewspaperListView, self).get_context_data(**kwargs)

        title = self.request.GET.get("title", "")

        context["search_form"] = NewspaperSearchForm(
            initial={"title": title}
        )

        return context

    def get_queryset(self):
        title = self.request.GET.get("title")

        if title:
            return self.queryset.filter(title__icontains=title)
        return self.queryset


class NewspaperDetailView(LoginRequiredMixin, generic.DetailView):
    model = Newspaper


class NewspaperCreateView(LoginRequiredMixin, generic.CreateView):
    model = Newspaper
    form_class = NewspaperForm
    success_url = reverse_lazy("catalog:newspaper-list")
    template_name = "catalog/newspaper_form.html"


class NewspaperUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Newspaper
    fields = "__all__"
    success_url = reverse_lazy("catalog:newspaper-list")
    template_name = "catalog/newspaper_form.html"


class NewspaperDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Newspaper
    success_url = reverse_lazy("catalog:newspaper-list")
    template_name = "catalog/newspaper_form_confirm_delete.html"


class RedactorListView(LoginRequiredMixin, generic.ListView):
    model = Redactor
    paginate_by = 5
    queryset = Redactor.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs) -> dict:
        context = super(RedactorListView, self).get_context_data(**kwargs)

        username = self.request.GET.get("username", "")

        context["search_form"] = RedactorSearchForm(
            initial={"username": username}
        )

        return context

    def get_queryset(self) -> None:
        username = self.request.GET.get("username")

        if username:
            return self.queryset.filter(username__icontains=username)
        return self.queryset


class RedactorDetailView(LoginRequiredMixin, generic.DetailView):
    model = Redactor


class RedactorCreateView(LoginRequiredMixin, generic.CreateView):
    model = Redactor
    form_class = RedactorCreateForm
    success_url = reverse_lazy("catalog:redactor-list")


class RedactorExperienceUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Redactor
    fields = ["years_of_experience"]
    success_url = reverse_lazy("taxi:redactor-list")


class RedactorUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Redactor
    form_class = RedactorExperienceUpdateForm
    success_url = reverse_lazy("catalog:redactor-list")


class RedactorDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Redactor
    success_url = reverse_lazy("catalog:redactor-list")


def test_session_view(request):
    request.session["newspaper"] = "Test session newspaper"
    return HttpResponse(
        "<h1>Test Session</h1>"
        f"<h4>Session data: {request.session['newspaper']}</h4>"
    )

templates/catalog/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="apple-touch-icon" sizes="76x76" href="/static/assets/img/apple-icon.png">
  <link rel="icon" type="image/png" href="/static/assets/img/favicon.png">

  <title>
    Newspaper Agency
  </title>

  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css"
        href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700"/>
  <!-- Nucleo Icons -->
  <link href="/static/assets/css/nucleo-icons.css" rel="stylesheet"/>
  <link href="/static/assets/css/nucleo-svg.css" rel="stylesheet"/>
  <!-- Font Awesome Icons -->
  <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
  <!-- Material Icons -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">
  <!-- CSS Files -->
  <link id="pagestyle" href="/static/assets/css/material-kit.css?v=3.0.0" rel="stylesheet"/>

</head>
<body class="presentation-page bg-gray-200">

{% include 'includes/navigation.html' %}

<header class="header-2">
  <div class="page-header min-vh-75 relative" style="background-image: url('/static/assets/img/bg2.jpg')">
    <span class="mask bg-gradient-primary opacity-4"></span>
    <div class="container">
      <div class="row">
        <div class="col-lg-7 text-center mx-auto">
          <h1 class="text-white pt-3 mt-n5">Newspaper Agency</h1>
          <p class="lead text-white mt-3">Service for managing newspaper with redactors and topics</p>
        </div>
      </div>
    </div>
  </div>
</header>
<div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6">
  <section class="pt-3 pb-4" id="count-stats">
    <div class="container">
      <div class="row">
        <div class="col-lg-9 mx-auto py-3">
          <div class="row">
            <div class="col-md-4 position-relative">
              <div class="p-3 text-center">
                <h1 class="text-gradient text-primary"><span id="state1"
                                                             countTo="{{ num_topics }}">{{ num_topics }}</span>+</h1>
                <h5 class="mt-3">Topics</h5>
                <p class="text-sm font-weight-normal">A newspaper contains news articles from around the world on
                  different topics</p>
              </div>
              <hr class="vertical dark">
            </div>
            <div class="col-md-4 position-relative">
              <div class="p-3 text-center">
                <h1 class="text-gradient text-primary"><span id="state2"
                                                             countTo="{{ num_newspapers }}">{{ num_newspapers }}</span>+
                </h1>
                <h5 class="mt-3">Newspapers</h5>
                <p class="text-sm font-weight-normal">World famous publications are collected in one catalog</p>
              </div>
              <hr class="vertical dark">
            </div>
            <div class="col-md-4">
              <div class="p-3 text-center">
                <h1 class="text-gradient text-primary" id="state3"
                    countTo="{{ num_redactors }}">{{ num_redactors }}</h1>
                <h5 class="mt-3">Redactors</h5>
                <p class="text-sm font-weight-normal">Redactors registered on our site</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!--   Core JS Files   -->
  <script src="/static/assets/js/core/popper.min.js" type="text/javascript"></script>
  <script src="/static/assets/js/core/bootstrap.min.js" type="text/javascript"></script>
  <script src="/static/assets/js/plugins/perfect-scrollbar.min.js"></script>
  <!--  Plugin for TypedJS, full documentation here: https://github.com/inorganik/CountUp.js -->
  <script src="/static/assets/js/plugins/countup.min.js"></script>
  <!--  Plugin for Parallax, full documentation here: https://github.com/dixonandmoe/rellax -->
  <script src="/static/assets/js/plugins/rellax.min.js"></script>
  <!--  Plugin for TiltJS, full documentation here: https://gijsroge.github.io/tilt.js/ -->
  <script src="/static/assets/js/plugins/tilt.min.js"></script>
  <!--  Plugin for Selectpicker - ChoicesJS, full documentation here: https://github.com/jshjohnson/Choices -->
  <script src="/static/assets/js/plugins/choices.min.js"></script>
  <!--  Plugin for Parallax, full documentation here: https://github.com/wagerfield/parallax  -->
  <script src="/static/assets/js/plugins/parallax.min.js"></script>
  <!-- Control Center for Material UI Kit: parallax effects, scripts for the example pages etc -->
  <!--  Google Maps Plugin    -->
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTTfWur0PDbZWPr7Pmq8K3jiDp0_xUziI"></script>
  <script src="/static/assets/js/material-kit.min.js?v=3.0.0" type="text/javascript"></script>
  <script type="text/javascript">
      if (document.getElementById('state1')) {
          const countUp = new CountUp('state1', document.getElementById("state1").getAttribute("countTo"));
          if (!countUp.error) {
              countUp.start();
          } else {
              console.error(countUp.error);
          }
      }
      if (document.getElementById('state2')) {
          const countUp1 = new CountUp('state2', document.getElementById("state2").getAttribute("countTo"));
          if (!countUp1.error) {
              countUp1.start();
          } else {
              console.error(countUp1.error);
          }
      }
      if (document.getElementById('state3')) {
          const countUp2 = new CountUp('state3', document.getElementById("state3").getAttribute("countTo"));
          if (!countUp2.error) {
              countUp2.start();
          } else {
              console.error(countUp2.error);
          }
      }
  </script>
</div>
</body>

</html>

templates/catalog/newspaper_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>Model: {{ newspaper.title }}</h1>

  <div class="ml-6">
    <h3>Redactors:</h3>

    {% for redactor in newspaper.redactors.all %}
      <hr>
      <p class="text-muted"><strong>Id:</strong>{{ redactor.id }}</p>
      <p>
        <strong>Full name:</strong>
        {{ redactor.first_name }} {{ redactor.last_name }}
      </p>
    {% endfor %}
  </div>
{% endblock %}

templates/catalog/newspaper_form.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} newspaper</h1>

  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <br>

    <input class="btn btn-primary" type="submit" value="Submit">
  </form>
{% endblock %}

templates/catalog/newspaper_form_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

  <h1>Delete Newspaper</h1>

  <p>Are you sure you want to delete the newspaper: {{ newspaper }}?</p>
  <p><i>All Newspapers will be delete</i></p>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-danger"/>
  </form>
{% endblock %}

templates/catalog/newspaper_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}


{% block content %}
  <h1>Newspaper list
    <a href="{% url 'catalog:newspaper-create' %}">+</a>
  </h1>
  <form action="" method="get">
    {{ search_form }}
    <input type="submit" value="Search" class="btn btn-primary">
  </form>

  {% if newspaper_list %}
    <table class="table">
      <tr style="background-color: rgb(232, 205, 231);">
        <th>ID</th>
        <th>Name</th>
        <th>Description</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
      {% for newspaper in newspaper_list %}
        <tr>
          <td>
            {{ newspaper.id }}
          </td>
          <td>
            <a href="{% url 'catalog:newspaper-detail' pk=newspaper.id %}">{{ newspaper.title }}</a>
          </td>
          <td>
            {{ newspaper.content }}
          </td>
          <td>
            <a href="{% url "catalog:newspaper-update" pk=newspaper.id %} ">UPDATE</a>
          </td>
          <td>
            <a href="{% url "catalog:newspaper-delete" pk=newspaper.id %} ">DELETE</a>
          </td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>There are no newspapers</p>
  {% endif %}

{% endblock %}

templates/catalog/redactor_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

  <h1>Delete redactor</h1>

  <p>Are you sure you want to delete the redactor: {{ redactor }}?</p>
  <p><i>All Newspapers will be delete</i></p>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-danger"/>
  </form>
{% endblock %}

templates/catalog/redactor_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>Name: {{ redactor.first_name }} {{ redactor.last_name }}
    <a href="{% url 'catalog:redactor-delete' pk=redactor.id %}" class="btn btn-danger link-to-page">Delete
    </a>
  </h1>


  <div class="ml-6">
    <h4>Information about redactor:</h4>

    <p><strong>Redactor's id:</strong> {{ redactor.id }}</p>
    <p><strong>Redactor's experience:</strong> {{ redactor.years_of_experience }} years <a
        href="{% url 'catalog:redactor-update' pk=redactor.id %}">Edit experience
    </a></p>
    <h8><strong>Available newspapers titles:</strong></h8>
    {% for newspaper in redactor.newspapers.all %}
      <ul>
        <li>{{ newspaper.title }}</li>
      </ul>

    {% endfor %}
  </div>
{% endblock %}

templates/catalog/redactor_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Create redactor</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/catalog/redactor_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}


{% block content %}
  <h1>Redactor List
    <a href="{% url 'catalog:redactor-create' %}">
      +
    </a>
  </h1>
  <form action="" method="get" class="form-inline" novalidate>
    {{ search_form }}
    <input type="submit" value="Search" class="btn btn-primary">
  </form>

  {% if redactor_list %}
    <table class="table">
      <tr style="background-color:rgb(232, 205, 231)">
        <th>ID</th>
        <th>Username</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Experience(years)</th>
      </tr>
      {% for redactor in redactor_list %}
        <tr>
          <td>{{ redactor.id }}</td>
          <td><a href="{% url 'catalog:redactor-detail' pk=redactor.id %}">{{ redactor.username }}
            {% if user == redactor %} (Me){% endif %}</a></td>
          <td>{{ redactor.first_name }}</td>
          <td>{{ redactor.last_name }}</td>
          <td>{{ redactor.years_of_experience }}</td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>There are no redactors in the service.</p>
  {% endif %}
{% endblock %}

templates/catalog/topic_form.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} topic</h1>

  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <br>

    <input class="btn btn-primary" type="submit" value="Submit">
  </form>
{% endblock %}

templates/catalog/topic_form_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

  <h1>Delete newspaper</h1>

  <p>Are you sure you want to delete the newspaper: {{ topic }}?</p>
  <p><i>All Newspapers will be delete</i></p>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-danger"/>
  </form>
{% endblock %}

templates/catalog/topic_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
<div class="bg-ex-gradient-animation">


  {% block content %}
    <h1>Topic list
      <a href="{% url 'catalog:topic-create' %}">+</a>
    </h1>
    <form action="" method="get">
      {{ search_form }}
      <input type="submit" value="Search" class="btn btn-primary">
    </form>
    {% if topic_list %}
      <table class="table">
        <tr style="background-color: rgb(232, 205, 231);">
          <th>ID</th>
          <th>Name</th>
          <th>Update</th>
          <th>Delete</th>
        </tr>

        {% for topic in topic_list %}
          <tr>
            <td>
              {{ topic.id }}
            </td>
            <td>
              {{ topic.name }}
            </td>
            <td>
              <a href="{% url "catalog:topic-update" pk=topic.id %} ">UPDATE</a>
            </td>
            <td>
              <a href="{% url "catalog:topic-delete" pk=topic.id %} ">DELETE</a>
            </td>
          </tr>
        {% endfor %}
      </table>
    {% else %}
      <p>There are no topic in agency</p>
    {% endif %}
  {% endblock %}